M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date ven. 17 juin 2022 11:05:16
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-17T11:05:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
%
G90
G05
T1
X4.6726Y-3.4203
T0
M30
